### ISSUE TITLE
ModuleNotFoundError: No module named 'propermab.structure.construction'

### ISSUE THREAD

**Issue by kehan777** [regeneron-mpds/propermab#2]
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from propermab import defaults
  File "/mnt/d/propermab/propermab/__init__.py", line 62, in <module>
    from . import structure as st
  File "/mnt/d/propermab/propermab/structure/__init__.py", line 64, in <module>
    from .construction import *
ModuleNotFoundError: No module named 'propermab.structure.construction'

**Comment by bianli-regn** [comment]
@kehan777 Thanks for your interest in the work and bringing up this ModuleNotFoundError. It has now been fixed.
